import translateFromTable from "../translators/translateFromTable";
import formatYear from "../translators/formatYear";
import formatZip from "../translators/formatZip";
import formatDob from "../translators/formatDob";
import formatCBCode from "../translators/formatCBCode";

export const translatorMaps = {
  awards: {
    "01": "AP Scholar",
    "02": "AP Scholar with Honor",
    "03": "AP Scholar with Distinction",
    "04": "State AP Scholar",
    "05": "National AP Scholar",
    "06": "National AP Scholar (Canada)",
    "07": "AP International Diploma",
    "08": "DoDEA AP Scholar",
    "09": "International AP Scholar",
    "12": "National AP Scholar (Bermuda)",
    "13": "AP Capstone Diploma",
    "14": "AP Seminar and Research Certificate",
    "15": "AP with WE service recognition",
  },
  bestLanguage: {
    "1": "English Only",
    "3": "English and Another",
    "4": "Another",
    "0": "No response",
  },
  exam: {
    "07": "US History",
    "13": "Art History",
    "14": "Drawing",
    "15": "2-D Art and Design",
    "16": "3-D Art and Design",
    "20": "Biology",
    "22": "Seminar",
    "23": "Research",
    "25": "Chemistry",
    "28": "Chinese Language and Culture",
    "31": "Computer Science A",
    "32": "Computer Science Principles",
    "33": "Computer Science AB",
    "34": "Microeconomics",
    "35": "Macroeconomics",
    "36": "English Language and Composition",
    "37": "English Literature and Composition",
    "40": "Environmental Science",
    "43": "European History",
    "48": "French Language and Culture",
    "51": "French Literature",
    "53": "Human Geography",
    "55": "German Language and Culture",
    "57": "US Government and Politics",
    "58": "Comparative Government and Politics",
    "60": "Latin",
    "61": "Latin Literature",
    "62": "Italian Language and Culture",
    "64": "Japanese Language and Culture",
    "66": "Calculus AB",
    "68": "Calculus BC",
    "69": "Calculus BC: AB Subscore",
    "75": "Music Theory",
    "76": "Music Aural Subscore",
    "77": "Music Non-Aural Subscore",
    "78": "Physics B",
    "80": "Physics C: Mechanics",
    "82": "Physics C: Electricity and Magnetism",
    "83": "Physics 1",
    "84": "Physics 2",
    "85": "Psychology",
    "87": "Spanish Language and Culture",
    "89": "Spanish Literature and Culture",
    "90": "Statistics",
    "93": "World History: Modern",
  },
  gender: {
    A: "Another",
    F: "Female",
    M: "Male",
    U: "Unknown",
  },
  gradeLevel: {
    "3": "< 9th grade",
    "4": "9th grade",
    "5": "10th grade",
    "6": "11th grade",
    "7": "12th grade",
    "8": "Not in high school",
    "11": "Unknown",
  },
  irregularityCodes: {
    "01": "Score not yet available - student will be contacted by 8/1",
    "02": "Score delayed - will be reported as soon as possible",
    "03": "Score delayed - will be reported as soon as possible",
    "04": "Score canceled - student’s choice per options received",
    "05": "Score delayed - will be reported as soon as possible",
    "06": "Score delayed - will be reported as soon as possible",
    "07": "Pending student response to options provided",
    "08": "Score delayed - will be reported as soon as possible",
    "09": "Score delayed - will be reported as soon as possible",
    "10": "Score delayed - will be reported as soon as possible",
    "12": "Score delayed - will be reported as soon as possible",
    "13": "Score delayed - will be reported as soon as possible",
    "16": "No score available: Makeup exam was requested but not taken",
    "17": "Score Canceled: Makeup exam was requested but not taken",
    "18": "Score delayed - will be reported as soon as possible",
    "19": "Score canceled",
    "20": "School reported undertiming of 5 minutes or less",
    "34": "School reported distraction during exam",
    "37": "Portion of exam lost - score projected from remainder",
    "38": "Media not scorable - score projected from remainder",
    "39": "School started exam late",
    "40": "School reported undertiming of more than 5 minutes",
    "42": "Portion unscorable - score projected from remainder",
    "44": "Score projected from multiple-choice section",
    "49": "Presentation score(s) not reported, projected from remainder",
    "51": "Score projected from free-response section",
    "57": "Score projected from multiple-choice and free-resp. sections",
    "66": "School reported overtiming of more than 5 minutes",
    "78": "Score projected from 75% of exam",
    "80": "Score delayed - will be reported as soon as possible",
    "81": "Score delayed - will be reported as soon as possible",
    "82": "Score delayed - will be reported as soon as possible",
    "83": "Score delayed - will be reported as soon as possible",
    "84": "Score delayed - will be reported as soon as possible",
    "85": "Score delayed - will be reported as soon as possible",
    "86": "Score delayed - will be reported as soon as possible",
    "87": "Score canceled due to missing portion of exam",
    "88": "Score delayed - will be reported as soon as possible",
    "89": "Score delayed - will be reported as soon as possible",
    "90": "Score delayed - will be reported as soon as possible",
    "91": "One or more performance tasks not scored",
    "92": "Score canceled",
    "93": "Score delayed - will be reported as soon as possible",
    "94": "Score canceled at student's request",
    "95": "Second exam canceled - was not authorized",
    "96": "Score not yet available",
    "97": "Score delayed - will be reported as soon as possible",
    "98": "Score withheld on college report at student's request",
  },
  raceEthnicity: {
    "1": "Cuban",
    "2": "Mexican",
    "3": "Puerto Rican",
    "4": "Other Hispanic or Latino",
    "5": "Non-Hispanic or Latino",
    "6": "American Indian or Alaska Native",
    "7": "Asian (Including Indian Subcontinent and Philippines Origin)",
    "8":
      "Black or African American (Including Africa and Afro-Caribbean Origin)",
    "9": "Native Hawaiian or Other Pacific Islander",
    "10": "White (Including Middle Estern Origin)",
    "11": "Other",
  },
  aggregateRaceEthnicity: {
    "0": "No response",
    "1": "American Indian / Alaska Native",
    "2": "Asian",
    "3": "Black / African American",
    "4": "Hispanic / Latino",
    "8": "Native Hawaiian or Other Pacific Islander",
    "9": "White",
    "10": "Other",
    "12": "Two or More Races, Non-Hispanic",
  },
};

export const config2019: TConfig = {
  awardData: {
    position: 26,
    count: 6,
    fields: [
      {
        position: 0,
        fieldName: "Award type",
        ifBlank: "",
        translate: translateFromTable(translatorMaps.awards),
      },
      {
        position: 1,
        fieldName: "Award year",
        ifBlank: "",
        translate: formatYear,
      },
    ],
  },
  scoreData: {
    position: 59,
    count: 30,
    fields: [
      {
        position: 0,
        fieldName: "Admin Year",
        ifBlank: "",
        translate: formatYear,
      },
      {
        position: 1,
        fieldName: "Exam",
        ifBlank: "",
        translate: translateFromTable(translatorMaps.exam),
      },
      { position: 2, fieldName: "Exam Grade", ifBlank: "" },
      {
        position: 3,
        fieldName: "Irregularity code #1",
        ifBlank: "",
        translate: translateFromTable(translatorMaps.irregularityCodes),
      },
      {
        position: 4,
        fieldName: "Irregularity code #2",
        ifBlank: "",
        translate: translateFromTable(translatorMaps.irregularityCodes),
      },
      {
        position: 5,
        fieldName: "Class section code",
        ifBlank: "",
      },
    ],
  },
  ethnicityData: {
    position: 243,
    fieldName: "Race / Ethnicity",
    ifBlank: "",
  },
  fields: [
    { position: 1, fieldName: "AP Number", ifBlank: "" },
    { position: 2, fieldName: "Last name", ifBlank: "" },
    { position: 3, fieldName: "First name", ifBlank: "" },
    { position: 4, fieldName: "Middle initial", ifBlank: "" },
    { position: 5, fieldName: "Street address 1", ifBlank: "" },
    { position: 6, fieldName: "Street address 2", ifBlank: "" },
    { position: 7, fieldName: "Street address 3", ifBlank: "" },
    { position: 8, fieldName: "State", ifBlank: "" },
    {
      position: 9,
      fieldName: "Zip code",
      ifBlank: "",
      translate: formatZip,
    },
    { position: 12, fieldName: "Country code", ifBlank: "" },
    {
      position: 13,
      fieldName: "Gender",
      ifBlank: "",
      translate: translateFromTable(translatorMaps.gender),
    },
    {
      position: 14,
      fieldName: "Date of birth",
      ifBlank: "",
      translate: formatDob,
    },
    {
      position: 14,
      fieldName: "Grade level",
      ifBlank: "",
      translate: translateFromTable(translatorMaps.gradeLevel),
    },
    {
      position: 17,
      fieldName: "Best language",
      ifBlank: "",
      translate: translateFromTable(translatorMaps.bestLanguage),
    },
    {
      position: 38,
      fieldName: "Institution College Board Code",
      ifBlank: "",
      translate: formatCBCode,
    },
    {
      position: 39,
      fieldName: "Institution name",
      ifBlank: "",
    },
    {
      position: 244,
      fieldName: "Aggregate Race / Ethnicity",
      ifBlank: "",
      translate: translateFromTable(translatorMaps.aggregateRaceEthnicity),
    },
  ],
};
